// Core.Vue.UI/app/app.vue
<script setup lang="ts">
	import { ref } from 'vue';
	import { App } from './app.ts';
	import Login from './pages/login/Login.vue';
	import Header from './pages/layout/header/Header.vue';
	import Footer from './pages/layout/footer/Footer.vue';

	const app = new App();
	const title = ref('Sign In');
</script>

<template>
	<div class="app">
		<Header></Header>
		<!-- <Login v-bind:title="title"></Login> -->
		<Footer></Footer>
	</div>
</template>

<style scoped>
</style>

// Core.UI/app/app.jsx
﻿import React from 'react';
import Header from './components/layout/header/header';
import Footer from './components/layout/footer/footer';
import Registration from './pages/registration/registration';
import './app.less';


class App extends React.Component {
    constructor(props) {
        super(props);
    }

    render() {
        return (
            <div>
                <Header/>
                Welcome to Adventure!
                <Registration />
                <Footer/>
            </div>
        );
    }
}

export default App;
