// Core.Angular.UI/app/modules/home/components/home/home.component.ts
import { Component, OnInit } from "@angular/core";
import { ActivatedRoute, Router } from "@angular/router";
import { faThList, faTasks } from '@fortawesome/free-solid-svg-icons';
import { NavigationItem } from "app/modules/common/components/layout/navigation/navigation-item/navigation-item.component";
import { NavigationItemModel } from "app/modules/common/models/navigation-item.model";
import { AdventuresComponent } from "app/modules/home/components/home/adventures/adventures.component";
import { ExperiencesComponent } from "app/modules/home/components/home/experiences/experiences.component";

@Component({
	selector: "app-home",
	templateUrl: "./home.component.html",
	styleUrls: ["./home.component.scss"]
})
export class HomeComponent implements OnInit {
	navItems: NavigationItemModel[];

	constructor(
		private readonly router: Router,
		private readonly route: ActivatedRoute
	) {
	}

	ngOnInit(): void {
		this.navItems = [
			{
				id: 1,
				name: "Adventures",
				icon: faThList,
				model: new NavigationItem(
					AdventuresComponent,
					{ title: "Adventures" }
				)
			},
			{
				id: 2,
				name: "Experiences",
				icon: faTasks,
				model: new NavigationItem(
					ExperiencesComponent,
					{ title: "Experiences" }
				)
			}
		] as NavigationItemModel[];
	}
}

<app-header></app-header>
<div class="home">
	<div class="container">
		<div class="row clearfix">
			<div class="col-sm-3">
				<app-navigation></app-navigation>
			</div>
			<div class="cols-sm-8">
			</div>
		</div>
	</div>
</div>
<app-footer></app-footer>

// Core.React.UI/app/pages/home/home.jsx
﻿import React from 'react';
import _ from 'lodash';
import Navigation from '../../pages/layout/navigation/navigation';
import AdventuresContainer from './adventures/adventuresContainer';
import ExperiencesContainer from './experiences/experiencesContainer';
import { faThList, faTasks } from '@fortawesome/free-solid-svg-icons'
import './home.less';

export default class Home extends React.Component {
	constructor(props) {
		super(props);
	}

	render() {
		const navigationItems = [
			{
				name: "adventures",
				title: "Adventures",
				icon: faThList,
				component: <AdventuresContainer/>
			},
			{
				name: "experiences",
				title: "Experiences",
				icon: faTasks,
				component: <ExperiencesContainer/>
			}
		];
		const active = _.first(navigationItems);

		return (
			<div className="home">
				<Navigation
					items={navigationItems}
					active={active}
				/>
			</div>
		);
	}
}
