// Core.UI/app/pages/layout/header/header.jsx
﻿import React from 'react';
import { Link } from 'react-router-dom';
import { Navbar, Nav, NavItem } from 'react-bootstrap';
import { LinkContainer } from 'react-router-bootstrap';
import AuthorizationHelper from 'app/helpers/authorizationHelper';
import './header.less';

class Header extends React.Component {
	constructor(props) {
		super(props);

		this.onLogout = this.onLogout.bind(this);
	}

	onLogout(event) {
		const { history, onLogout } = this.props;
		const data = { history };
		onLogout(data);
	}

	renderLoginPanel() {
		const isAuthorized = AuthorizationHelper.isAuthorized();

		if (isAuthorized) {
			const { authorizationData } = this.props;

			return (
				<Nav pullRight={true}>
					{authorizationData &&
						<NavItem>Hello, {authorizationData.firstName}!</NavItem>
					}
					<NavItem onClick={this.onLogout}>Logout</NavItem>
				</Nav>
			);
		}

		return (
			<Nav pullRight={true}>
				<LinkContainer to="/registration" replace>
					<NavItem>Registration</NavItem>
				</LinkContainer>
				<LinkContainer to="/login" replace>
					<NavItem>Login</NavItem>
				</LinkContainer>
			</Nav>
		);
	}

	render() {
		const authorizationPanel = this.renderLoginPanel();

		return (
			<div className="header">
				<Navbar inverse collapseOnSelect>
					<Navbar.Header>
						<Navbar.Brand>
							<Link to="/home" replace>
								Home
							</Link>
						</Navbar.Brand>
						<Navbar.Toggle />
					</Navbar.Header>

					<Navbar.Collapse>
						<Nav>
							<LinkContainer to="/summary" replace>
								<NavItem >Summary</NavItem>
							</LinkContainer>
						</Nav>

						{authorizationPanel}
					</Navbar.Collapse>
				</Navbar>
			</div>
		);
	}
}

export default Header;

// Core.Vue.UI/app/pages/layout/header/Header.vue
<script setup lang="ts">
	import { ref } from 'vue';
	import { userService } from '../../../services/userService.ts';
	import { AuthorizationHelper } from '../../../helpers/authorization.helper.ts';
	import router from '../../../router/router.ts';

	const authorizationData = AuthorizationHelper.getAuthorizationData();

	const firstName = authorizationData ? ref(authorizationData.firstName) : null;

	const onLogout = async () => {
		await userService.logout();

		AuthorizationHelper.removeAuthorizationData();
		router.push({ name: 'login', replace: true });
	};
</script>

<template>
	<header class="container">
		<div class="content">
			<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
				<div class="container-fluid">
					<router-link to="/home" class="navbar-brand">Home</router-link>
					<button
						class="navbar-toggler"
						type="button"
						data-bs-toggle="collapse"
						data-bs-target="#navbarText"
						aria-controls="navbarText"
						aria-expanded="false"
						aria-label="Toggle navigation"
					>
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarText">
						<ul class="navbar-nav me-auto mb-2 mb-lg-0">
							<li class="nav-item">
								<router-link to="/summary" class="nav-link">Summary</router-link>
							</li>
						</ul>
					</div>

					<div class="justify-content-end navbar-nav">
						<div class="nav-item">
							<a
								role="button"
								class="nav-link"
								tabindex="0"
								href="#"
							>
								Hello, {{ firstName }}!
							</a>
						</div>
						<div class="nav-item" @click="onLogout">
							<a
								role="button"
								class="nav-link"
								tabindex="0"
								href="#"
							>
								Logout
							</a>
						</div>
					</div>
				</div>
			</nav>
		</div>
	</header>
</template>

<style scoped>
</style>
