// Core.Angular.UI/app/modules/common/components/layout/header/header.component.ts
import { Component, OnInit } from "@angular/core";
import { Router } from "@angular/router";
import { UserService } from "app/modules/account/services/user.service";
import { AuthorizationHelper } from "app/modules/common/helpers/authorization.helper";
import { firstValueFrom } from "rxjs";

@Component({
	selector: "app-header",
	templateUrl: "./header.component.html",
	styleUrls: ["./header.component.scss"]
})
export class HeaderComponent implements OnInit {
	firstName: string;

	constructor(
		private readonly userService: UserService,
		private readonly router: Router
	) {
	}

	ngOnInit(): void {
		const authorizationData = AuthorizationHelper.getAuthorizationData();
		this.firstName = authorizationData.firstName;
	}

	async onLogout(): Promise<void> {
		await firstValueFrom(this.userService.logout());

		AuthorizationHelper.removeAuthorizationData();
		this.router.navigate(['/account']);
	}
}

<header class="container">
	<div class="content">
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
			<div class="container-fluid">
				<a
					class="navbar-brand"
					[routerLink]="'/home'"
				>
					Home
				</a>
				<button
					class="navbar-toggler"
					type="button"
					data-bs-toggle="collapse"
					data-bs-target="#navbarText"
					aria-controls="navbarText"
					aria-expanded="false"
					aria-label="Toggle navigation"
				>
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarText">
					<ul class="navbar-nav me-auto mb-2 mb-lg-0">
						<li class="nav-item">
							<a
								class="nav-link"
								[routerLink]="'/summary'"
							>
								Summary
							</a>
						</li>
					</ul>
				</div>

				<div class="justify-content-end navbar-nav">
					<div class="nav-item">
						<a
							role="button"
							class="nav-link"
							tabindex="0"
							href="#"
						>
							Hello, {{firstName}}!
						</a>
					</div>
					<div class="nav-item" (click)="onLogout($event)">
						<a
							role="button"
							class="nav-link"
							tabindex="0"
							href="#"
						>
							Logout
						</a>
					</div>
				</div>
			</div>
		</nav>
	</div>
</header>

// Core.Vue.UI/app/pages/layout/header/Header.vue
<script setup lang="ts">
	import { ref } from 'vue';
	import { userService } from '../../../services/user.service.ts';
	import { AuthorizationHelper } from '../../../helpers/authorization.helper.ts';
	import router from '../../../router/router.ts';

	const authorizationData = AuthorizationHelper.getAuthorizationData();

	const firstName = authorizationData ? ref(authorizationData.firstName) : null;

	const onLogout = async () => {
		await userService.logout();

		AuthorizationHelper.removeAuthorizationData();
		router.push({ name: 'login', replace: true });
	};
</script>

<template>
	<header class="container">
		<div class="content">
			<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
				<div class="container-fluid">
					<router-link to="/home" class="navbar-brand">Home</router-link>
					<button
						class="navbar-toggler"
						type="button"
						data-bs-toggle="collapse"
						data-bs-target="#navbarText"
						aria-controls="navbarText"
						aria-expanded="false"
						aria-label="Toggle navigation"
					>
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarText">
						<ul class="navbar-nav me-auto mb-2 mb-lg-0">
							<li class="nav-item">
								<router-link to="/summary" class="nav-link">Summary</router-link>
							</li>
						</ul>
					</div>

					<div class="justify-content-end navbar-nav">
						<div class="nav-item">
							<a
								role="button"
								class="nav-link"
								tabindex="0"
								href="#"
							>
								Hello, {{ firstName }}!
							</a>
						</div>
						<div class="nav-item" @click="onLogout">
							<a
								role="button"
								class="nav-link"
								tabindex="0"
								href="#"
							>
								Logout
							</a>
						</div>
					</div>
				</div>
			</nav>
		</div>
	</header>
</template>

<style scoped>
</style>
