// Core.Angular.UI/app/modules/home/components/home/adventures/adventures.component.ts
import { Component, OnInit } from "@angular/core";
import { AdventureModel } from "app/modules/home/models/adventure.model";
import { AdventureService } from "app/modules/home/services/adventure.service";
import { firstValueFrom } from "rxjs";
import { NgbModal } from "@ng-bootstrap/ng-bootstrap";
import { AdventureComponent } from "./adventure/adventure.component";
import { AuthorizationHelper } from "app/modules/common/helpers/authorization.helper";

@Component({
	selector: "app-adventures",
	templateUrl: "./adventures.component.html",
	styleUrls: ["./adventures.component.scss"]
})
export class AdventuresComponent implements OnInit {
	adventures: AdventureModel[];

	constructor(
		private readonly modalService: NgbModal,
		private readonly adventureService: AdventureService
	) {
	}

	async ngOnInit(): Promise<void> {
		await this.refreshAdventures();
	}

	async refreshAdventures(): Promise<void> {
		const adventures = await firstValueFrom(this.adventureService.getAdventures());

		this.adventures = adventures;
	}

	async onCreate(): Promise<void> {
		const { result, model } = await this.showAdventureModal(
			{
				name: '',
				description: '',
				startsOn: null,
				endsOn: null
			});

		if (result) {
			const authorizationData = AuthorizationHelper.getAuthorizationData();
			const request = {
				...model,
				startsOn: (new Date(Date.UTC(model.startsOn.year, model.startsOn.month - 1, model.startsOn.day))).toISOString(),
				endsOn: (new Date(Date.UTC(model.endsOn.year, model.endsOn.month - 1, model.endsOn.day))).toISOString(),
				createdById: authorizationData.id
			};

			await firstValueFrom(this.adventureService.create(request));
		}

		await this.refreshAdventures();
	}

	async onEdit(adventure: any): Promise<void> {
		const { result, model } = await this.showAdventureModal(adventure);

		if (result) {
			const authorizationData = AuthorizationHelper.getAuthorizationData();
			const request = {
				...model,
				startsOn: (new Date(Date.UTC(model.startsOn.year, model.startsOn.month - 1, model.startsOn.day))).toISOString(),
				endsOn: (new Date(Date.UTC(model.endsOn.year, model.endsOn.month - 1, model.endsOn.day))).toISOString(),
				createdById: authorizationData.id
			};

			await firstValueFrom(this.adventureService.update(request));
		}

		await this.refreshAdventures();
	}

	async onRemove(id: number): Promise<void> {
		await firstValueFrom(this.adventureService.remove(id));

		await this.refreshAdventures();
	}

	async showAdventureModal(model: any): Promise<{ result: boolean, model: any }> {
		const modalReference = this.modalService.open(AdventureComponent);

		modalReference.componentInstance.title = "Adventure";
		modalReference.componentInstance.data = model;

		return await modalReference.result;
	}
}

<div class="adventures">
	<div class="adventure-title row">
		<div class="col">
			<h3>Adventures</h3>
			<button type="button" class="btn btn-primary btn-sm" (click)="onCreate()">
				Create
			</button>
		</div>
	</div>
	<ng-container *ngIf="true">
		<ng-container *ngFor="let adventure of adventures">
			<div class="adventure bg-light row">
				<div class="col">
					<div>Name: {{adventure.name}}</div>
				</div>
				<div class="col">
					<div>Description: {{adventure.description}}</div>
				</div>
				<div class="col">
					<button class="btn btn-danger btn-sm" (click)="onRemove(adventure.id)">
						Remove
					</button>
					<button class="btn btn-primary btn-sm" (click)="onEdit(adventure)">
						Edit
					</button>
				</div>
			</div>
		</ng-container>
	</ng-container>
</div>

// Core.React.UI/app/pages/home/adventures/adventures.jsx
﻿import React from 'react';
import _ from 'lodash';
import Adventure from 'app/components/adventure/adventure';
import { Row, Col, Button } from 'react-bootstrap';
import GenericModal from 'app/components/common/genericModal/genericModal';
import './adventures.less';

export default class Adventures extends React.Component {
	constructor(props) {
		super(props);
		const { authorizationData, experiences } = props;

		this.state = {
			authorizationData: authorizationData || null,
			isPopupVisible: false,
			model: {
				id: null,
				name: "",
				description: "",
				createdBy: null,
				startsOn: new Date(),
				endsOn: new Date(),
				experiences: [],
				participants: []
			}
		};

		this.onSave = this.onSave.bind(this);
		this.onRemove = this.onRemove.bind(this);
		this.onEdit = this.onEdit.bind(this);

		this.props.onGetAllAdventures();
		this.props.onGetAllExperiences();
	}

	onSave = data => {
		const { authorizationData } = this.props;

		const {
			id,
			name,
			firstName,
			lastName,
			email
		} = authorizationData;

		data.experiences = data.experiences.map(function(x) {
			return {
				name: x.label,
				id: x.value
			}
		});

		data.createdBy = {
			id: id,
			name: name,
			firstName: firstName,
			lastName: lastName,
			email: email
		};

		if (_.isNull(data.id || null)) {
			this.props.onCreate(data);
		} else {
			this.props.onUpdate(data);
		}

		this.setState({ isPopupVisible: false });
		this.props.onGetAllAdventures();
	};

	onRemove = model => {
		if (_.isNull(model)) {
			return;
		}
		this.props.onRemove(model);
		this.props.onGetAllAdventures();
	};

	onEdit = model => {
		this.setState({
			isPopupVisible: true,
			model: model
		});
	};

	render() {
		const { adventures, experienceOptions } = this.props;
		const { model, isPopupVisible } = this.state;

		model.experienceOptions = experienceOptions || [];

		const adventuresList = adventures.map((adventure, index) => {
			return (
				<Row key={index} className={"adventure bg-light"}>
					<Col>
						<div>Name: {adventure.name}</div>
					</Col>
					<Col>
						<div>Description: {adventure.description}</div>
					</Col>
					<Col>
						<Button onClick={() => this.onRemove(adventure)} className={"btn btn-danger btn-sm"}>
							Remove
						</Button>
						<Button onClick={() => this.onEdit(adventure)} className={"btn btn-primary btn-sm"}>
							Edit
						</Button>
					</Col>
				</Row>
			);
		});
		
		return (
			<div className={"adventures"}>
				<Row className={"adventure-title"}>
					<Col>
						<h3>Adventures</h3>
						<Button
							onClick={() => this.onEdit({
								id: null,
								name: "",
								description: "",
								createdBy: null,
								startsOn: new Date(),
								endsOn: new Date(),
								experiences: [],
								participants: []
							})}
							disabled={this.isPopupVisible}
							className={"btn btn-primary btn-sm"}
						>
							Create
						</Button>
					</Col>
				</Row>

				{adventuresList}

				<GenericModal
					title={"Adventure"}
					isVisible={isPopupVisible}
					onSave={this.onSave}
					component={Adventure}
					model={model}
				/>
			</div>
		);
	}
}
