// Core.UI/app/pages/registration/registration.jsx
﻿import React from 'react';
import './registration.less';

class Registration extends React.Component {
	constructor(props) {
		super(props);

		this.state = {
			name: "",
			firstName: "",
			lastName: "",
			email: "",
			password: "",
			confirmedPassword: ""
		};

		this.onChange = this.onChange.bind(this);
		this.onSignUp = this.onSignUp.bind(this);
	}

	onChange(event) {
		const checkboxTargetType = "checkbox";
		const target = event.target;
		const value = target.type === checkboxTargetType
			? target.checked
			: target.value;
		const name = target.name;

		this.setState({
			[name]: value
		});
	}

	onSignUp(event) {
		this.props.onSignUp(this.state);
	}

	render() {
		return (
			<div className="registration">
				<h3>Sign Up</h3>
				<form onSubmit={this.onSignUp}>
					<input name="name" value={this.state.name} onChange={this.onChange} type="text" placeholder="Login" />
					<input name="firstName" value={this.state.firstName} onChange={this.onChange} type="text" placeholder="First Name" />
					<input name="lastName" value={this.state.lastName} onChange={this.onChange} type="text" placeholder="Last Name" />
					<input name="email" value={this.state.email} onChange={this.onChange} type="text" placeholder="Email" />
					<input name="password" value={this.state.password} onChange={this.onChange} type="password" placeholder="Password" />
					<input name="confirmedPassword" value={this.state.confirmedPassword} onChange={this.onChange} type="password" placeholder="Confirm Password" />
					<input type="submit" value="Sign Up" />
				</form>
			</div>
		);
	}
}

export default Registration;

// Core.Angular.UI/app/modules/account/components/registration/registration.component.ts
import { Component, OnInit } from "@angular/core";
import { ActivatedRoute, Router } from "@angular/router";
import { faArrowAltCircleLeft, IconDefinition } from '@fortawesome/free-solid-svg-icons';

@Component({
	selector: "app-registration",
	templateUrl: "./registration.component.html",
	styleUrls: ["./registration.component.scss"]
})
export class RegistrationComponent implements OnInit {
	FaArrowAltCircleLeft: IconDefinition;

	model: any;

	constructor(
		private readonly router: Router,
		private readonly route: ActivatedRoute
	) {
		this.FaArrowAltCircleLeft = faArrowAltCircleLeft;
	}

	ngOnInit(): void {
		this.model = {
			name: null,
			firstName: null,
			lastName: null,
			email: null,
			password: null,
			confirmedPassword: null
		};
	}

	onSignUp(): void {
		const model = this.model;
	}
}

<div class="registration">
	<div class="title">
		<h3>Sign Up</h3>

		<a
			ngbNavLink
			href="#/account/login"
		>
			<fa-icon class="fa-2x" [icon]="FaArrowAltCircleLeft"></fa-icon>
		</a>
	</div>

	<form (ngSubmit)="onSignUp()" (keyup.enter)="onSignUp()">
		<div class="form-group">
			<label for="name" class="form-label">Name</label>
			<input id="name" name="name" class="form-control" type="text" [(ngModel)]="model.name" placeholder="Login" />
		</div>
		<div class="mt-2">
			<label for="firstName" class="form-label">First Name</label>
			<input id="firstName" name="firstName" class="form-control" type="text" [(ngModel)]="model.firstName" placeholder="First Name" />
		</div>
		<div class="mt-2">
			<label for="lastName" class="form-label">Last Name</label>
			<input id="lastName" name="lastName" class="form-control" type="text" [(ngModel)]="model.lastName" placeholder="Last Name" />
		</div>
		<div class="mt-2">
			<label for="email" class="form-label">Email</label>
			<input id="email" name="email" class="form-control" type="text" [(ngModel)]="model.email" placeholder="Email" />
		</div>
		<div class="mt-2">
			<label for="password" class="form-label">Password</label>
			<input id="password" name="password" class="form-control" type="password" [(ngModel)]="model.password" placeholder="Password" />
		</div>
		<div class="mt-2">
			<label for="confirmedPassword" class="form-label">Confirm Password</label>
			<input id="confirmedPassword" class="form-control" type="password" name="confirmedPassword" [(ngModel)]="model.confirmedPassword" placeholder="Confirm Password" />
		</div>
		<div class="mt-4">
			<button class="form-control btn btn-primary" type="submit">Sign Up</button>
		</div>
	</form>
</div>
