// Core.Vue.UI/app/pages/account/login/Login.vue
<script setup lang="ts">
	import { ref, reactive, computed, watch, onMounted, onUpdated, onUnmounted } from 'vue';
	import { userService } from '../../../services/user.service.ts';
	import { AuthorizationHelper } from '../../../helpers/authorization.helper.ts';
	import { push } from '../../../router/router.ts';

	const model = reactive({
		userName: '',
		userPassword: ''
	});

	const onLogin = async () => {
		const data = await userService.login({ name: model.userName, password: model.userPassword });
		AuthorizationHelper.setAuthorizationData(data);

		if (AuthorizationHelper.isAuthorized()) {
			push("home");
		}
	};

	const onRegister = () => {
		push("registration");
	};
</script>

<template>
	<div class="login">
		<h3>Sign In</h3>

		<form v-on:submit="onLogin">
			<div class="form-group">
				<label for="name" class="form-label">Name</label>
				<input v-model="model.userName" id="name" name="name" class="form-control" type="text" placeholder="Login" />
			</div>
			<div class="form-group mt-2">
				<label for="password" class="form-label">Password</label>
				<input v-model="model.userPassword" id="password" name="name" class="form-control" type="password" placeholder="Password" />
			</div>
			<div class="form-group mt-4">
				<button class="form-control btn btn-primary" type="submit" >Sign In</button>
			</div>
			<div class="form-group mt-4">
				<a
					class="form-control btn btn-secondary" 
					role="button"
					href="#/account/registration"
					v-on:click="onRegister"
				>
					Sign Up
				</a>
			</div>
		</form>
	</div>
</template>

<style scoped>
	.login {
		form {
			margin: 0 auto;
			max-width: 320px;
		}

		h3 {
			max-width: 320px;
			margin: 0 auto;
			padding: 20px 0px;
		}

		.error {
			margin: 5px 0;
		}
	}
</style>

// Core.Angular.UI/app/modules/account/components/login/login.component.ts
import { Component, OnInit } from "@angular/core";
import { ActivatedRoute, Router, ParamMap } from "@angular/router";
import { UserService } from "../../services/user.service";
import { UserModel } from "../../models/user.model";
import { AuthorizationHelper } from "app/modules/common/helpers/authorization.helper";
import { firstValueFrom } from "rxjs";

@Component({
	selector: "app-login",
	templateUrl: "./login.component.html",
	styleUrls: ["./login.component.scss"]
})
export class LoginComponent implements OnInit {
	model: any;

	constructor(
		private readonly router: Router,
		private readonly route: ActivatedRoute,
		private readonly userService: UserService
	) {
	}

	ngOnInit(): void {
		this.model = {
			name: null,
			password: null
		};
	}

	async onSignIn(): Promise<void> {
		const model = this.model;
		const userModel = {
			name: model.name,
			password: model.password
		} as UserModel;

		const data = await firstValueFrom(this.userService.login(userModel));

		AuthorizationHelper.setAuthorizationData(data);

		if (AuthorizationHelper.isAuthorized()) {
			this.router.navigate(['/home']);
		}
	}
}

<div class="login">
	<h3>Sign In</h3>

	<form (ngSubmit)="onSignIn()" (keyup.enter)="onSignIn()">
		<div class="form-group">
			<label for="name" class="form-label">Name</label>
			<input id="name" name="name" class="form-control" type="text" [(ngModel)]="model.name" placeholder="Login" />
		</div>
		<div class="form-group mt-2">
			<label for="password" class="form-label">Password</label>
			<input id="password" name="name" class="form-control" type="password" [(ngModel)]="model.password" placeholder="Password" />
		</div>
		<div class="form-group mt-4">
			<button class="form-control btn btn-primary" type="submit" >Sign In</button>
		</div>
		<div class="form-group mt-4">
			<a class="form-control btn btn-secondary" role="button" href="#/account/registration">Sign Up</a>
		</div>
	</form>
</div>
