// Core.Angular.UI/app/modules/home/components/home/adventures/adventures.component.ts
import { Component, Input, OnInit } from "@angular/core";
import { AdventureModel } from "app/modules/home/models/adventure.model";
import { AdventureService } from "app/modules/home/services/adventure.service";
import { firstValueFrom } from "rxjs";

@Component({
	selector: "app-adventures",
	templateUrl: "./adventures.component.html",
	styleUrls: ["./adventures.component.scss"]
})
export class AdventuresComponent implements OnInit {
	adventures: AdventureModel[];

	constructor(
		private readonly adventureService: AdventureService
	) {
	}

	async ngOnInit(): Promise<void> {
		const adventures = await firstValueFrom(this.adventureService.getAdventures());

		this.adventures = adventures;
	}
}

<div class="adventures">
	<div class="adventure-title row">
		<div class="col">
			<h3>Adventures</h3>
			<button type="button" class="btn btn-primary btn-sm">
				Create
			</button>
		</div>
	</div>
	<ng-container *ngIf="true">
		<ng-container *ngFor="let adventure of adventures">
			<div class="adventure bg-light row">
				<div class="col">
					<div>Name: {{adventure.name}}</div>
				</div>
				<div class="col">
					<div>Description: {{adventure.description}}</div>
				</div>
				<div class="col">
					<button class="btn btn-danger btn-sm">
						Remove
					</button>
					<button class="btn btn-primary btn-sm">
						Edit
					</button>
				</div>
			</div>
		</ng-container>
	</ng-container>
</div>

// Core.Vue.UI/app/pages/adventures/Adventures.vue
<script setup lang="ts">
	import { reactive, onMounted } from 'vue';
	import { adventureService } from '../../services/adventureService.ts';
	import AdventureModel from '../../models/adventure.model.ts';

	const model = reactive({
		adventures: [] = [] as AdventureModel[]
	});

	onMounted(async () => {
		try {
			const adventures = await adventureService.getAdventuresList();
			model.adventures = adventures
		} catch (err) {
			console.error('Failed to load adventures:', err);
			model.adventures = [] as AdventureModel[];
		}
	});

	const onRemove = async (adventureId: number) => {
		await adventureService.removeAdventure(adventureId);

		model.adventures = model.adventures
			.filter(a => a.id !== adventureId);
	};

	const onEdit = (adventure: any) => {

	};
</script>

<template>
	<div class="adventures">
		<div class="adventure-title row">
			<div class="col">
				<h3>Adventures</h3>
			</div>
		</div>
		<div class="adventure bg-light row" v-for="adventure in model.adventures" :key="adventure.id">
			<div class="col">
				<div>Name: {{adventure.name}}</div>
			</div>
			<div class="col">
				<div>Description: {{adventure.description}}</div>
			</div>
			<div class="col">
			<button class="btn btn-danger btn-sm" @click="onRemove(adventure.id)">
				Remove
			</button>
			<button class="btn btn-primary btn-sm" @click="onEdit(adventure)">
				Edit
			</button>
		</div>
	</div>

	</div>
</template>

<style lang="scss" scoped>
	.adventures {
		.adventure-title {
			margin-top: 10px;

			.col {
				h3 {
					display: inline-block;
				}

				button {
					display: inline-block;
					float: right;
					margin: 5px 0 0 5px;
				}
			}
		}

		.adventure {
			padding: 10px 0 10px 0;
			margin: 5px 0 5px 0;

			.col {
				button {
					display: inline-block;
					float: right;
					margin-left: 5px;
				}
			}
		}
	}
</style>
