// Core.Angular.UI/app/modules/common/components/layout/footer/footer.component.ts
import { Component, OnInit } from "@angular/core";

@Component({
	selector: "app-footer",
	templateUrl: "./footer.component.html",
	styleUrls: ["./footer.component.scss"]
})
export class FooterComponent implements OnInit {
	constructor() {
	}

	ngOnInit(): void {}
}
<footer class="footer fixed-bottom">
	<div class="container">
		<div class="content">		
			<nav class="navbar navbar-expand navbar-dark bg-dark">
				<div class="container">
					<span>© Pavel Kaliukhovich</span>
				</div>
			</nav>
		</div>
	</div>
</footer>

// Core.Vue.UI/app/pages/layout/footer/Footer.vue
<script setup lang="ts">
	import { ref } from 'vue';
	import { Footer } from './footer.ts';

	const footer = new Footer();
</script>

<template>
	<footer class="footer fixed-bottom">
		<div class="container">
			<div class="content">
				<nav class="navbar navbar-expand navbar-dark bg-dark">
					<div class="container">
						<span>© Pavel Kaliukhovich</span>
					</div>
				</nav>
			</div>
		</div>
	</footer>
</template>

<style>
	.footer {
		color: #ffffff;
	}
</style>
