// Core.Vue.UI/app/pages/layout/footer/Footer.vue
<script setup lang="ts">
	import { ref } from 'vue';
	import { Footer } from './footer.ts';

	const footer = new Footer();
</script>

<template>
	<footer class="footer fixed-bottom">
		<div class="container">
			<div class="content">
				<nav class="navbar navbar-expand navbar-dark bg-dark">
					<div class="container">
						<span>© Pavel Kaliukhovich</span>
					</div>
				</nav>
			</div>
		</div>
	</footer>
</template>

<style>
	.footer {
		color: #ffffff;
	}
</style>

// Core.React.UI/app/pages/layout/footer/footer.jsx
﻿import React from 'react';
import { Container, Navbar, Nav } from 'react-bootstrap';
import './footer.less';

export default class Footer extends React.Component {
	constructor(props) {
		super(props);
	}

	render() {
		return (
			<footer className="footer fixed-bottom">
				<Container>
					<Navbar variant="dark" bg="dark">
						<Container>
							<span>&#169; Pavel Kaliukhovich</span>
						</Container>
					</Navbar>
				</Container>
			</footer>
		);
	}
}
