// Core.React.UI/app/pages/login/login.jsx
﻿import React from 'react';
import { FormGroup, FormLabel, FormControl, Alert, Button } from 'react-bootstrap';
import './login.less';

export default class Login extends React.Component {
	constructor(props) {
		super(props);

		this.state = {
			name: "",
			password: ""
		};

		this.onChange = this.onChange.bind(this);
		this.onLogin = this.onLogin.bind(this);
	}

	onChange(event) {
		const checkboxTargetType = "checkbox";
		const target = event.target;
		const value = target.type === checkboxTargetType
			? target.checked
			: target.value;
		const name = target.name;

		this.setState({
			[name]: value
		});
	}

	onLogin(event) {
		event.preventDefault();
		this.props.onLogin(this.state);
	}

	render() {
		const { error } = this.props;
		const { name, password } = this.state;

		return (
			<div className="login">
				{error &&
					<Alert bsStyle="danger" className="error">
						{error.message}
					</Alert>
				}
				<h3>Sign In</h3>
				<form onSubmit={this.onLogin}>
					<FormGroup>
						<FormLabel>Name</FormLabel>
						<FormControl name="name" value={name} onChange={this.onChange} type="text" placeholder="Login" />
					</FormGroup>
					<FormGroup className="mt-2">
						<FormLabel>Password</FormLabel>
						<FormControl name="password" value={password} onChange={this.onChange} type="password" placeholder="Password" />
					</FormGroup>
					<FormGroup className="mt-4">
						<FormControl type="submit" value="Sign In" className={"btn btn-primary"} />
					</FormGroup>
					<FormGroup className="mt-4">
						<Button variant="secondary" href="#/registration" className="form-control">Sign Up</Button>
					</FormGroup>
				</form>
			</div>
		);
	}
}

// Core.Vue.UI/app/pages/account/login/Login.vue
<script setup lang="ts">
	import { reactive } from 'vue';
	import { userService } from '../../../services/userService.ts';
	import { AuthorizationHelper } from '../../../helpers/authorization.helper.ts';
	import router from '../../../router/router.ts';

	const model = reactive({
		userName: '',
		userPassword: ''
	});

	const onLogin = async (e) => {
		e.preventDefault();

		const data = await userService.login({ name: model.userName, password: model.userPassword });
		AuthorizationHelper.setAuthorizationData(data);

		if (AuthorizationHelper.isAuthorized()) {
			router.push({ name: 'home', replace: true });
		}
	};

	const onRegister = (e) => {
		e.preventDefault();

		router.push({ name: 'registration' });
	};
</script>

<template>
	<div class="login">
		<h3>Sign In</h3>

		<form v-on:submit="onLogin">
			<div class="form-group">
				<label for="name" class="form-label">Name</label>
				<input v-model="model.userName" id="name" name="name" class="form-control" type="text" placeholder="Login" />
			</div>
			<div class="form-group mt-2">
				<label for="password" class="form-label">Password</label>
				<input v-model="model.userPassword" id="password" name="name" class="form-control" type="password" placeholder="Password" />
			</div>
			<div class="form-group mt-4">
				<button class="form-control btn btn-primary" type="submit" >Sign In</button>
			</div>
			<div class="form-group mt-4">
				<a
					class="form-control btn btn-secondary"
					role="button"
					href="#"
					@click="onRegister"
				>
					Sign Up
				</a>
			</div>
		</form>
	</div>
</template>

<style scoped>
	.login {
		form {
			margin: 0 auto;
			max-width: 320px;
		}

		h3 {
			max-width: 320px;
			margin: 0 auto;
			padding: 20px 0px;
		}

		.error {
			margin: 5px 0;
		}
	}
</style>
